const path = {
  PUBLIC: "/",
  HOME: "",
  SEARCH: "search",
  DETAIL_PRODUCT: "detail-product/:id/:storeId",
  LIST_PRODUCT: "list-product",
  LOGIN: "login",
  SETTING: "setting",
  STORE: "STORE",
  DETAIL_STORE: "detail-store/:id",
  ORDER: "order",
  ORDER_CART: "order-cart",
  ADD_LOCATION: "add-location",
  ADD_ADDRESS: "add-address",
  REGISTER_STORE_CHOOSE: "register-choose",
  REGISTER_STORE: "register-store",
  ADDNEW_ADDRESS: "add-new-address",
  EDIT_PROFILE_USER: "edit-profile-user",
  CHANGE_PASSWORD: "change-password",
  WALLET: "wallet",
  DEPOSIT_WALLET: "deposit-wallet",
  WITHDRAW_WALLET: "withdraw-wallet",
  UPDATE_BANK: "update-bank",
  UPDATE_ADDRESS: "update-address/:id",
  BUY_PRODUCT: "buy-product/:id",
  DETAIL_PRODUCT_AGENT: "detail-product-agent/:id",
  WITHDRAW_ADMIN: "with-draw",
  TRANSFORM_HISTORY: "transform-history",
  BOOK_PRODUCT: "book-product/:id/:userId",
};
export default path;
